### ISSUE TITLE
Add bootstrap (or otherwise) to increase display size when mobile

### ISSUE THREAD

**Issue by alexmorley** [alexmorley/CodeOfConduct.Builder#17]
Refactor to include the [bootstrap](https://www.bootstrapcdn.com/) to improve display on mobile.

**Comment by amylaun** [comment]
I think bootstrap is a little more than is needed to fix display on mobile. It would be pretty simple to add some CSS to make the builder page responsive. I can put together a PR.

**Comment by alexmorley** [comment]
fixed in #28 and #32 :tada:
