### ISSUE TITLE
Empty strings in JSONs show as empty bullets in Code of Conduct.

### ISSUE THREAD

**Issue by gerardogalvez** [alexmorley/CodeOfConduct.Builder#23]
[ContributorCovenant.json](https://github.com/alexmorley/CodeOfConduct.Builder/blob/master/app/resources/ContributorCovenant.json#L24) and [confcodeofconduct.json](https://github.com/alexmorley/CodeOfConduct.Builder/blob/master/app/resources/confcodeofconduct.json#L18) have empty strings at the end of their respective `howto` arrays, displaying them in the Code of Conduct as empty bullets as shown in the screenshots. Either remove those empty strings or check for empty strings when adding those elements.

<img width="897" alt="screen shot 2017-10-02 at 3 04 45 pm" src="https://user-images.githubusercontent.com/8509232/31096954-55ef1780-a783-11e7-9b22-ba16b81a2693.png">

**Comment by gerardogalvez** [comment]
I can submit a PR for this and #24 in case it's something it should be done.

**Comment by alexmorley** [comment]
@gerardogalvez yes please. You can be pretty heavy-handed with the javascript as its very rough atm. I think maybe it would be good to have a default saying "this code of conduct doesn't include info about X; maybe add something yourself?". What do you think?

**Comment by gerardogalvez** [comment]
That sounds great! I also thought about not including the section at all but that having it there gives a clue about what the Code could have.
