### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by alexmorley** [alexmorley/CodeOfConduct.Builder#33]
Thinking of logo-fying the Code of Conduct Builder.

Inspiration or Ideas anyone? 
Idea 1:
![software-carp](https://user-images.githubusercontent.com/13655521/31251462-e502e624-aa15-11e7-8497-90db3a794df8.png)

**Comment by ajkendal** [comment]
@alexmorley 

I would love to help.

Is there a certain Color Palette we have to stick too?

**Comment by harleo** [comment]
@alexmorley 
I'm also up to create a logo, working on it right now.
The project definitely needs something like that.

**Comment by harleo** [comment]
Some ideas I've thrown together real quick, focusing on the logo itself, colors later:

![cocb_mockups](https://user-images.githubusercontent.com/18539354/31256508-4515ad90-aa33-11e7-9cd9-fbd436eae090.png)

**Comment by stevenanthonyrevo** [comment]
Some more options for the logo design below: 
![codeofconductbuilder-logos](https://user-images.githubusercontent.com/8505293/31262249-d4b22bec-aa27-11e7-91d3-8f65c72e853f.png)

**Comment by alexmorley** [comment]
Wow those are all amazing! :tada: Going to have to have a serious think about what fits best. :thinking:

**Comment by harleo** [comment]
If you have any feedback just shout it, can change anything.

**Comment by alexmorley** [comment]
Would it be easy to create a PR with a folder called logo which has .svg (or other vector graphic format) of these ideas? Then a) you'll be added to the contributors & b) I can see how they look on the site.

**Comment by harleo** [comment]
@alexmorley Sure thing.

**Comment by harleo** [comment]
@alexmorley 
Sorry for the wait.
#34

**Comment by JDMex** [comment]
![codeofconduct-logo-by-jdmex](https://user-images.githubusercontent.com/1133677/31300518-9a723bb0-aaa0-11e7-84fa-3d0c488bdf01.jpg)

**Comment by alexmorley** [comment]
Woah, enough ideas to consider for now. Thanks everyone! (pls submit a PR with logo's in a vector format -.svg ideally- if you haven't already.)
